export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_SUCCEDED = 'FETCH_POSTS_SUCCEDED'
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED'
export const FETCH_POSTS_CANCEL = 'FETCH_POSTS_CANCEL'
