export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_SUCCEDED = 'FETCH_POSTS_SUCCEDED'
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED'
export const FETCH_POSTS_CANCEL = 'FETCH_POSTS_CANCEL'

export const UPDATE_POST_IN_PROGRESS = 'UPDATE_POST_IN_PROGRESS'
export const UPDATE_POST_SUCCEDED = 'UPDATE_POST_SUCCEDED'
export const UPDATE_POST_FAILED = 'UPDATE_POST_FAILED'

export const ADD_NEW_POST = 'ADD_NEW_POST'
export const ADD_NEW_POST_SUCCEDED = 'ADD_NEW_POST_SUCCEDED'
export const ADD_NEW_POST_FAILED = 'ADD_NEW_POST_FAILED'

export const SELECT_POST_TO_EDIT = 'SELECT_POST_TO_EDIT'
export const SELECT_POST_TO_EDIT_FAILED = 'SELECT_POST_TO_EDIT_FAILED'

export const LOAD_SELECTED_POST_SUCCEDED = 'LOAD_SELECTED_POST_SUCCEDED'
export const LOAD_SELECTED_POST_FAILED = 'LOAD_SELECTED_POST_FAILED'